name: 同步存储库操作
on:
  push:
  schedule:
    # 每天北京时间0点同步
    - cron:  '0 16 * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/pterodactyl-china'
          dst: 'gitee/pterodactyl-china'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "documentation"
          force_update: true
      - name: Mirror the Github organization repos to Gitee.(panel)
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/pterodactyl-china'
          dst: 'gitee/vlssu'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          mappings: "panel=>pterodactyl-panel"
          static_list: "panel"
          force_update: true
